### ISSUE TITLE
GC6153 port to ESP32 and datasheet

### ISSUE THREAD

**Issue by Habarnam2** [YanbinH/MIMXRT1060_GC6153#2]
Hello. 
I wold like to use GC6153 on a small mobile robot based on esp32.
I want to use this sensor because it is cheap and because of the SPI interface it uses less pins on the controller.

With your permission I would like to port the GC6153 code you wrote to esp32.
Also, because I'm outside China, I can't download the datasheet from csdn.net. Can you please share the datasheet of the sensor?

Thank you.

**Comment by YanbinH** [comment]
Hello , I have already uploaded the datasheet.

**Comment by Habarnam2** [comment]
Thank you for your fast response. I can't find it. Can you post the link, please?

**Comment by YanbinH** [comment]
Sure, It's in the README file.
https://github.com/YanbinH/MIMXRT1060_GC6153/files/8473399/AE-QVGA-3005.GC6153.CSP.DataSheet.release.V1.0.pdf
